config/routes.rb
KoodiKysely::Application.routes.draw do

  get "code_question_review_controller/index"

  resources :english_mooc_participants
  resources :english_moocs

  resources :pages

  resources :students
  resources :code_questions
  root :to => 'students#new' #pages#index' 
  

end

app/models/code_question.rb
class CodeQuestion < ActiveRecord::Base
  attr_accessible  :no_indent, :no_indent_comment, :bad_variable_names, :bad_variable_names_comment , :no_air, :no_air_comment
  attr_accessible :extra_comments, :extra_comments_comment, :bad_method_names, :bad_method_names_comment
  attr_accessible :everything_in_main, :everything_in_main_comment , :too_complex_iffs, :too_complex_iffs_comment , :unconsistent_names, :unconsistent_names_comment , :many_methods, :many_methods_comment
  belongs_to :student
end

app/models/english_mooc.rb
class EnglishMooc < ActiveRecord::Base
  attr_accessible :yksi, :kaksi, :kolme, :nelja, :viisi, :kuusi, :seitseman, :kahdeksan, :yhdekan, :kymmenen
  belongs_to :english_mooc_participant
end

app/models/english_mooc_participant.rb
class EnglishMoocParticipant < ActiveRecord::Base
  attr_accessible :details, :programmed_before, :student_number, :year, :hours, :language, :gender, :nationality, :native_language
  has_many :english_moocs #students answers
  # attr_accessible :title, :body
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :details, :programmed_before, :student_number, :year, :hours, :language, :gender
  has_many :code_questions #students answers

  def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
      tmp_header = []
      tmp_header << Student.attribute_names
      tmp_header << CodeQuestion.attribute_names
	    csv << tmp_header.flatten
	    all.each do |std|
	      tpm_std = []
        tpm_std << std.attributes.collect{|a| a[1]}
        tpm_std << std.code_questions.first.attributes.collect{|a| a[1]}
        csv << tpm_std.flatten
	    end
    end
  end

end

app/controllers/application_controller.rb
require 'csv'
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/code_question_review_controller_controller.rb
class CodeQuestionReviewControllerController < ApplicationController
  def index
  	@student = Student.all
    respond_to do |format|
      format.html
      format.json do
      	render :json => @student.to_json
      end
      format.csv { render text: Student.to_csv}
  	end

  end

end

app/controllers/code_questions_controller.rb
class CodeQuestionsController < ApplicationController
  include Wicked::Wizard

  steps :part1, :part2, :part3, :part4, :part5, :part6, :part7, :part8, :success


  def show
    @student =  Student.find_by_id(session[:student_id])

    @code_question = CodeQuestion.find_by_id(session[:code_question_id])
    redirect_to new_student_path unless @student and @code_question 
    session[:auth] = "foobar"
    render_wizard
  end

  def update
    @student = Student.find_by_id(session[:student_id])
    @code_question = CodeQuestion.find_by_id(session[:code_question_id])
    @code_question.update_attributes(params[:code_question]) 
    
    render_wizard @code_question
  end
end

app/controllers/english_mooc_participants_controller.rb
class EnglishMoocParticipantsController < ApplicationController
 def new
    @title = "mooc.fi Survey"
    @student = EnglishMoocParticipant.new
    @kiitos = "Than you for taking our survey!" if session[:auth]
    session[:user_id] = nil
    session[:code_question_id] = nil
    session[:auth] = nil
  end

  def create
    @title = "mooc.fi Survey"
    @student = EnglishMoocParticipant.create(params[:english_mooc_participant])
    @student.request = request.inspect
    @student.ip = request.ip
    @student.save!
    #session[:student_id] = @student.id
    @code_question = @student.english_moocs << EnglishMooc.create
    #session[:english_mooc_id] = @code_question.id
    redirect_to  english_mooc_path(@code_question)
  end

  def index
    raise "found it"
  end

  def show

  end
end

app/controllers/english_moocs_controller.rb
class EnglishMoocsController < ApplicationController

  def create

  end

  def update
    @title = "mooc.fi Survey"
    @eng = EnglishMooc.find_by_id(params[:id])
    @eng.update_attributes(params[:english_mooc])
    session[:auth] = :ok
    redirect_to new_english_mooc_participant_path

  end

  def show
    @title = "mooc.fi Survey"
    redirect_to edit_english_mooc_path params[:id]
  end

  def edit
    @title = "mooc.fi Survey"
    @mooc_answer = EnglishMooc.find_by_id(params[:id])
  end


end

app/controllers/mooc_controller.rb
class MoocController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @kiitos = "Kiitos kyselyyn vastaamisesta" if session[:auth]
    session[:user_id] = nil
    session[:code_question_id] = nil
    session[:auth] = nil
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
    @kiitos = "Kiitos kyselyyn vastaamisesta" if session[:auth]
    session[:user_id] = nil
    session[:code_question_id] = nil
    session[:auth] = nil
  end

  def create
    @student = Student.create(params[:student])
    session[:student_id] = @student.id
    @code_question = @student.code_questions.create
    session[:code_question_id] = @code_question.id
    redirect_to  code_question_path(:part1)
  end

  def index
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_question_review_controller_helper.rb
module CodeQuestionReviewControllerHelper
end

app/helpers/code_questions_helper.rb
module CodeQuestionsHelper
end

app/helpers/english_mooc_helper.rb
module EnglishMoocHelper
end

app/helpers/english_mooc_participant_helper.rb
module EnglishMoocParticipantHelper
end

app/helpers/mooc_helper.rb
module MoocHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/code_question_review_controller/index.html.haml
.page-header
%table.table.table-striped
  %thead
    %tr
      - Student.attribute_names.each do |s|
        %th= s
      - CodeQuestion.attribute_names.each do |n|
        %th= n
  %tbody
    - @student.each do |s|
      %tr
        - s.attributes.each do |attr|
          %td= attr[1]
        - if s.code_questions.first
          - s.code_questions.first.attributes.each do |a|
            %td= a[1]

app/views/code_questions/everything_in_main.html.erb
<h2>A</h2>

<pre  class="sh_java">
ArrayList&lt;Integer&gt; luvut = new ArrayList&lt;Integer&gt;();
luvut.add(4);
luvut.add(3);
luvut.add(3);

System.out.println("luvut alussa:");
for (int luku : luvut) {
    System.out.println(luku);
}


while (luvut.contains(Integer.valueOf(3))) {
    luvut.remove(Integer.valueOf(3));         
}

System.out.println("luvut poiston jälkeen:");

for (int luku : luvut) {
    System.out.println(luku);
}

</pre>    

<h2>B</h2> 
<pre  class="sh_java">
ArrayList&lt;Integer&gt; luvut = new ArrayList&lt;Integer&gt;();
lisaa(luvut, 4, 3, 2);

System.out.println("luvut alussa:");
tulosta(luvut);

poista(luvut, 3);

System.out.println("luvut poiston jälkeen:");
tulosta(luvut);

</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <%= f.label :everything_in_main ,"A" %>
  <%= f.radio_button :everything_in_main, 1 %>
  <%= f.label :everything_in_main ,"B" %>
  <%= f.radio_button :everything_in_main, 2 %>
  <%= f.label :everything_in_main , "EOS" %>
  <%= f.radio_button :everything_in_main, 3 %> <br>
  <%= f.text_area :everything_in_main_comment %>
  <br>

  <%= f.submit "Seuraava" %>

 <% end %>

app/views/code_questions/extra_comments.html.erb
<h2>A</h2>

<pre class="sh_java">
int leveys = 2;
int korkeus = 4;
int pintaAla = leveys * korkeus;

System.out.println(“Pinta-ala: “ + pintaAla);
</pre>    

<h2>B</h2> 
<pre class="sh_java">
int leveys = 2; // leveys on 2
int korkeus = 4; // korkeus on 4
int pintaAla = leveys * korkeus; // pinta-ala on leveys * korkeus

System.out.println(“Pinta-ala: “ + pintaAla); // tulostetaan pinta-ala
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <%= f.label :extra_comments ,"A" %>
  <%= f.radio_button :extra_comments, 1 %>
  <%= f.label :extra_comments ,"B" %>
  <%= f.radio_button :extra_comments, 2 %>
  <%= f.label :extra_comments , "EOS" %>
  <%= f.radio_button :extra_comments, 3 %> <br>
  <%= f.text_area :extra_comments_comment %>
  <br>

  <%= f.submit "Seuraava" %>

 <% end %>

app/views/code_questions/no_air.html.erb
<h2>A</h2>

<pre class="sh_java">
while ( true ) {
   System.out.println("osaan ohjelmoida!");
   System.out.print("jatketaanko (ei lopettaa)? ");
   String komento = lukija.nextLine();
   if ( komento.equals("ei") ) {
       break;
   }
}
System.out.println("kiitos ja kuulemiin.");

</pre>    

<h2>B</h2> 
<pre class="sh_java">
while ( true ) {
   System.out.println("osaan ohjelmoida!");

   System.out.print("jatketaanko (ei lopettaa)? ");
   String komento = lukija.nextLine();
   if ( komento.equals("ei") ) {
       break;
   }
}
System.out.println("kiitos ja kuulemiin.");
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <%= f.label :no_air ,"A" %>
  <%= f.radio_button :no_air, 1 %>
  <%= f.label :no_air ,"B" %>
  <%= f.radio_button :no_air, 2 %>
  <%= f.label :no_air , "EOS" %>
  <%= f.radio_button :no_air, 3 %> <br>
  <%= f.text_area :no_air_comment %>
  <br>

  <%= f.submit "Seuraava" %>

 <% end %>

app/views/code_questions/no_indent.html.erb
<h2>A</h2>

<pre class="sh_java">
Scanner lukija = new Scanner(System.in);

System.out.print("Kuinka vanha olet: ");
int ika = Integer.parseInt(lukija.nextLine());

if( ika > 0 ) {
    System.out.println("Tervetuloa!");
} else {
    System.out.println("Huijaat!");
}
</pre>    

<h2>B</h2> 
<pre  class="sh_java">
Scanner lukija = new Scanner(System.in);

System.out.print("Kuinka vanha olet: ");
int ika = Integer.parseInt(lukija.nextLine());

if( ika > 0 ) {
System.out.println("Tervetuloa!");
} else {
System.out.println("Huijaat!");
}
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <%= f.label :no_indent ,"A" %>
  <%= f.radio_button :no_indent, 1 %>
  <%= f.label :no_indent ,"B" %>
  <%= f.radio_button :no_indent, 2 %>
  <%= f.label :no_indent , "EOS" %>
  <%= f.radio_button :no_indent, 3 %> <br>
  <%= f.text_area :no_indent_comment %>
  <br>

  <%= f.submit "Seuraava" %>

 <% end %>

app/views/code_questions/part1.html.erb
<h1>Kysymys 1/8</h1>

<h3>Koodi A</h3>

<pre class="sh_java">
Scanner lukija = new Scanner(System.in);

System.out.print("Kuinka vanha olet: ");
int ika = Integer.parseInt(lukija.nextLine());

if( ika > 0 ) {
    System.out.println("Tervetuloa!");
} else {
    System.out.println("Huijaat!");
}
</pre>    

<h3>Koodi B</h3> 
<pre  class="sh_java">
Scanner lukija = new Scanner(System.in);

System.out.print("Kuinka vanha olet: ");
int ika = Integer.parseInt(lukija.nextLine());

if( ika > 0 ) {
System.out.println("Tervetuloa!");
} else {
System.out.println("Huijaat!");
}
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  <p>Mielestäni...</p>
  
  <%= f.radio_button :no_indent, "A" %> <%= f.label :no_indent ,"Koodi A on parempi" %>  <br> 
  <%= f.radio_button :no_indent, "B" %> <%= f.label :no_indent ,"Koodi B on parempi" %>  
  <br>
  <%= f.radio_button :no_indent, "EOS" %> <%= f.label :no_indent , "En osaa sanoa" %><br>
  <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :no_indent_comment, :size => '15x4' %>
  <br>

  <%= f.submit "Seuraava", :class=>"btn btn-primary"%>

 <% end %>

app/views/code_questions/part2.html.erb
<h1>Kysymys 2/8</h1>
<h3>Koodi A</h3>

<pre  class="sh_java">
Scanner l = new Scanner(System.in);

System.out.print("Kenelle sanotaan hei: ");
String x = l.nextLine();

System.out.print("Hei " + x);
</pre>    

<h3>Koodi B</h3> 
<pre class="sh_java">
Scanner lukija = new Scanner(System.in);

System.out.print("Kenelle sanotaan hei: ");
String nimi = lukija.nextLine();

System.out.print("Hei " + nimi);
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
   <p>Mielestäni...</p>
  <%= f.radio_button :bad_variable_names, "A" %> 
  <%= f.label :bad_variable_names ,"Koodi A on parempi" %>
  <br>
  <%= f.radio_button :bad_variable_names, "B" %>
  <%= f.label :bad_variable_names ,"Koodi B on parempi" %>
  <br>
  <%= f.radio_button :bad_variable_names, "EOS" %> 
  <%= f.label :bad_variable_names , "En osaa sanoa" %>
  <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :bad_variable_names_comment, :size => '15x4' %>
  <br>

  <%= f.submit "Seuraava", :class => "btn btn-primary" %>

 <% end %>

app/views/code_questions/part3.html.erb
<h1>Kysymys 3/8</h1>
<h3>Koodi A</h3>

<pre class="sh_java">
while ( true ) {
   System.out.println("osaan ohjelmoida!");
   System.out.print("jatketaanko (ei lopettaa)? ");
   String komento = lukija.nextLine();
   if ( komento.equals("ei") ) {
       break;
   }
}
System.out.println("kiitos ja kuulemiin.");

</pre>    

<h3>Koodi B</h3> 
<pre class="sh_java">
while ( true ) {
  
   System.out.println("osaan ohjelmoida!");

   System.out.print("jatketaanko (ei lopettaa)? ");
   String komento = lukija.nextLine();
   if ( komento.equals("ei") ) {
       break;
   }
}
System.out.println("kiitos ja kuulemiin.");
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  <p>Mielestäni...</p>
  <%= f.radio_button :no_air, "A" %>
  <%= f.label :no_air ,"Koodi A on perempi" %>
  <br>
  <%= f.radio_button :no_air, "B" %>
  <%= f.label :no_air ,"Koodi B on parempi" %>
  <br>
  <%= f.radio_button :no_air, "EOS" %>
  <%= f.label :no_air , "En osaa sanoa" %>
   <br>
   <br>
   <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :no_air_comment, :size => '15x4' %>
  <br>

  <%= f.submit "Seuraava", :class => 'btn btn-primary' %>

 <% end %>

app/views/code_questions/part4.html.erb
<h1>Kysymys 4/8</h1>
<h3>Koodi A</h3>

<pre class="sh_java">
int leveys = 2;
int korkeus = 4;
int pintaAla = leveys * korkeus;

System.out.println(“Pinta-ala: “ + pintaAla);
</pre>    

<h3>Koodi B</h3> 
<pre class="sh_java">
int leveys = 2; // leveys on 2
int korkeus = 4; // korkeus on 4
int pintaAla = leveys * korkeus; // pinta-ala on leveys * korkeus

System.out.println(“Pinta-ala: “ + pintaAla); // tulostetaan pinta-ala
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  <p>Mielestäni...</p>
  <%= f.radio_button :extra_comments, "A" %>
  <%= f.label :extra_comments ,"Koodi A on parempi" %>
  <br>
  <%= f.radio_button :extra_comments, "B" %>
  <%= f.label :extra_comments ,"Koodi B on parempi" %>
  <br>
  <%= f.radio_button :extra_comments, "EOS" %> 
  <%= f.label :extra_comments , "En osaa sanoa" %>
  <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :extra_comments_comment, :size=>'15x4' %>
  <br>

  <%= f.submit "Seuraava", :class=>'btn btn-primary' %>

 <% end %>

app/views/code_questions/part5.html.erb
<h1>Kysymys 5/8</h1>
<h3>Koodi A</h3>

<pre class="sh_java">
Henkilo pekka = new Henkilo();
pekka.jumppaa();
pekka.zzz();
pekka.panttaa();
pekka.print();
</pre>    

<h3>Koodi B</h3> 
<pre class="sh_java">
Henkilo pekka = new Henkilo();
pekka.liiku();
pekka.nuku();
pekka.opiskele();
pekka.kerroOlo();
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <p>Mielestäni...</p>
  <%= f.radio_button :bad_method_names, "A" %>
  <%= f.label :bad_method_names ,"Koodi A on parempi" %>
  <br>
  <%= f.radio_button :bad_method_names, "B" %>
  <%= f.label :bad_method_names ,"Koodi B on parempi" %>
  <br>
  <%= f.radio_button :bad_method_names, "EOS" %>
  <%= f.label :bad_method_names , "En osaa sanoa" %>
  <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :bad_method_names_comment, :size=>'15x4' %>
  <br>

  <%= f.submit "Seuraava", :class=>'btn btn-primary' %>

 <% end %>

app/views/code_questions/part6.html.erb
<h1>Kysymys 6/8</h1>
<h3>Koodi A</h3>

<pre  class="sh_java">
ArrayList&lt;Integer&gt; luvut = new ArrayList&lt;Integer&gt;();
luvut.add(4);
luvut.add(3);
luvut.add(3);

System.out.println("luvut alussa:");
for (int luku : luvut) {
    System.out.println(luku);
}

while (luvut.contains(Integer.valueOf(3))) {
    luvut.remove(Integer.valueOf(3));         
}

System.out.println("luvut poiston jälkeen:");

for (int luku : luvut) {
    System.out.println(luku);
}

</pre>    

<h3>Koodi B</h3> 
<pre  class="sh_java">
ArrayList&lt;Integer&gt; luvut = new ArrayList&lt;Integer&gt;();
lisaa(luvut, 4, 3, 2);

System.out.println("luvut alussa:");
tulosta(luvut);

poista(luvut, 3);

System.out.println("luvut poiston jälkeen:");
tulosta(luvut);

</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  <p>Mielestäni...</p>
  <%= f.radio_button :everything_in_main, "A" %>
  <%= f.label :everything_in_main ,"Koodi A on parempi" %>
  <br>
  <%= f.radio_button :everything_in_main, "B" %>
  <%= f.label :everything_in_main ,"Koodi B on parempi"  %>
  <br>
  <%= f.radio_button :everything_in_main, "EOS" %> 
  <%= f.label :everything_in_main , "En osaa sanoa" %>
  <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>  
  <br>
  <%= f.text_area :everything_in_main_comment, :size=>'15x4' %>
  <br>

  <%= f.submit "Seuraava", :class=>'btn btn-primary' %>

 <% end %>

app/views/code_questions/part7.html.erb
<h1>Kysymys 7/8</h1>
<h3>Koodi A</h3>

<pre class="sh_java">
Tiedosto tiedosto = new Tiedosto("paivakirja.txt"); 
tiedosto.avaa();
String tiedot = tiedosto.lue();
tiedosto.lopeta();

System.out.println(tiedot);</pre>    

<h3>Koodi B</h3> 
<pre  class="sh_java">
Tiedosto tiedosto = new Tiedosto("paivakirja.txt"); 
tiedosto.avaa();
String tiedot = tiedosto.lue();
tiedosto.sulje();

System.out.println(tiedot);
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  <p>Mielestäni...</p>
  <%= f.radio_button :unconsistent_names, "A" %>
  <%= f.label :unconsistent_names ,"Koodi A on parempi" %>
  <br>
  <%= f.radio_button :unconsistent_names, "B" %>
  <%= f.label :unconsistent_names ,"Koodi B on parempi" %>
  <br>
  <%= f.radio_button :unconsistent_names, "EOS" %>
  <%= f.label :unconsistent_names , "En osaa sanoa" %>
   <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :unconsistent_names_comment, :size=>'15x4' %>
  <br>

  <%= f.submit "Seuraava", :class=>'btn btn-primary' %>

 <% end %>

app/views/code_questions/part8.html.erb
<h1>Kysymys 8/8</h1>
<h3>Koodi A</h3>

<pre class="sh_java">
int vuosi = 2013;
        
if ( vuosi % 400 == 0 ) {
    System.out.println("Vuosi on karkausvuosi!");
} else {
    if ( vuosi % 100 == 0 ) {
        System.out.println("Vuosi ei ole karkausvuosi!");
    } else {
        if ( vuosi % 4 == 0 ) {
            System.out.println("Vuosi on karkausvuosi!");
        } else {
            System.out.println("Vuosi ei ole karkausvuosi!");
        }
    }
}
</pre>    

<h3>Koodi B</h3> 
<pre  class="sh_java">
int vuosi = 2013;

if ( vuosi % 4 != 0 ) {
    System.out.println("Vuosi ei ole karkausvuosi!");
    return;
}

if ( vuosi % 400 == 0 ) {
    System.out.println("Vuosi on karkausvuosi!");
    return;
}

if ( vuosi % 100 == 0 ) {
    System.out.println("Vuosi ei ole karkausvuosi!");
    return;
}

System.out.println("Vuosi on karkausvuosi!");
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <p>Mielestäni...</p>
  <%= f.radio_button :too_complex_iffs, "A" %>
  <%= f.label :too_complex_iffs ,"Koodi A on parempi" %>
  <br>
  <%= f.radio_button :too_complex_iffs, "B" %>
  <%= f.label :too_complex_iffs ,"Koodi B on parempi" %>
  <br>
  <%= f.radio_button :too_complex_iffs, "EOS" %>
  <%= f.label :too_complex_iffs , "En osaa sanoa" %>
   <br>
  <br>
  <%= f.label "Vapaamuotoinen perustelu:" %>
  <br>
  <%= f.text_area :too_complex_iffs_comment, :size=>'15x4' %>
  <br>

  <%= f.submit "Tallenna", :class=>'btn btn-primary' %>

 <% end %>

app/views/code_questions/success.html.haml
%h1 Kiitos kyselyyn vastaamisesta

= button_to "Vastaa kyselyyn uudelleen tästä", new_student_path, :method => :get, :class => "btn btn-primary"

app/views/code_questions/unconsistent_names.html.erb
<h2>A</h2>

<pre class="sh_java">
int vuosi = 2013;
        
if ( vuosi % 400 == 0 ) {
    System.out.println("Vuosi on karkausvuosi!");
} else {
    if ( vuosi % 100 == 0 ) {
        System.out.println("Vuosi ei ole karkausvuosi!");
    } else {
        if ( vuosi % 4 == 0 ) {
            System.out.println("Vuosi on karkausvuosi!");
        } else {
            System.out.println("Vuosi ei ole karkausvuosi!");
        }
    }
}
</pre>    

<h2>B</h2> 
<pre  class="sh_java">
int vuosi = 2013;

if ( vuosi % 4 != 0 ) {
    System.out.println("Vuosi ei ole karkausvuosi!");
    return;
}

if ( vuosi % 400 == 0 ) {
    System.out.println("Vuosi on karkausvuosi!");
    return;
}

if ( vuosi % 100 == 0 ) {
    System.out.println("Vuosi ei ole karkausvuosi!");
    return;
}

System.out.println("Vuosi on karkausvuosi!");
</pre>



<%= form_for @code_question, :url => wizard_path, :method => :put do |f| %>
  
  <%= f.label :too_complex_iffs ,"A" %>
  <%= f.radio_button :too_complex_iffs, 1 %>
  <%= f.label :too_complex_iffs ,"B" %>
  <%= f.radio_button :too_complex_iffs, 2 %>
  <%= f.label :too_complex_iffs , "EOS" %>
  <%= f.radio_button :too_complex_iffs, 3 %> <br>
  <%= f.text_area :too_complex_iffs_comment %>
  <br>

  <%= f.submit "Seuraava" %>

 <% end %>

app/views/english_mooc_participants/_form.html.haml
%h1 Background

= form_for @student do |f|
  %p TMC account:
  = f.text_field :student_number 
  %br
  = f.label "Year of birth:"
  %br
  = f.text_field :year
  %br
  = f.label "Gender:"
  %br
  = f.radio_button :gender, 'M' 
  = f.label "Male"
  %br
  = f.radio_button :gender, 'N'
  = f.label "female" 
  %br
  = f.radio_button :gender, 'O'
  %span Other/I don't want to tell
  %br
  %br


  = f.label "Nationality:"
  %br
  = f.text_field :nationality
  %br
  = f.label "Native language:"
  %br
  = f.text_field :native_language
  %br
  %br

  = f.label "Do you have any programming experience?"
  %br

  = f.radio_button :programmed_before, true
  = f.label "Yes"
  %br
  = f.radio_button :programmed_before, false
  = f.label "No"

  %br
  %br
  = f.label "If yes, which programming languages"
  %br
  = f.text_area :language, :size => '20x4', class: 'input-xlarge'
  %br
  = f.label "If yes, how many hours approximately:"
  %br
  = f.number_field :hours 
  %br
  = f.submit 'Next page', class: 'btn btn-primary btn-large'

app/views/english_mooc_participants/index.html.haml
%h1 Student#index
%p Find me in app/views/student/index.html.haml

app/views/mooc/index.html.haml
%h1 Mooc#index
%p Find me in app/views/mooc/index.html.haml

app/views/students/new.html.haml
-if @kiitos
  %div{:class => "alert alert-success" }
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, @kiitos, :id => "flash_success"


%p.center.lead Tässä kyselyssä tutkimme, minkälaista ohjelmakoodia aloittelevat ohjelmoijat pitävät hyvänä. Vastaa kysymyksiin oman tuntemuksesi pohjalta, sinun ei tarvitse ymmärtää ohjelmaa tai ohjelmakoodia. Voit aina myös antaa vapaamuotoisen perustelun vastauksellesi.

%div.container
= link_to "as", code_question_review_controller_index_path
= render(:partial => "form")